### ISSUE TITLE
Support for DRF 3.0

### ISSUE THREAD

**Issue by gabriel-amram** [miki725/django-rest-framework-bulk#23]
Hello, 
DRF has introduced some significant changes in some of the logic regarding the Serializer.
For example, there is no more `pre_save`, but `perform_create` and `perform_update` instead that this package relies upon.
Another thing is `request.DATA` that is being deprecated and `serializer.object` that became `serializer.validated_data`.

Is there a workkaround for the time being so that we could still use DRF 3.0 with DRF-bulk?

Thanks!

**Comment by kevin-brown** [comment]
I just wrote a huge answer on Stack Overflow about doing this for the general case, as it has come up quite a few times since 3.0 was released.

http://stackoverflow.com/a/27871396/359284

It may be useful to those looking to implement it for this package. I do believe it is possible to make it compatible for both DRF 2 and 3, [it might make you cry though](https://github.com/kevin-brown/drf-json-api/commit/f281144006b4639a87332cc3fed967e51c8bbf69). Since the current PR is open, I'll take a look at it this weekend to see if there are any easy fixes that can be made.

**Comment by miki725** [comment]
@kevin-brown thank you. Ive been so busy for the last couple of weeks and didnt had a chance yet to look into this. I would love to see DRF2 and DRF3 support however if there is no "straight-forward" way of doing that without doing crazy things, I would rather have 2 branches going, one for each DRF version and keep releasing them both.
